name: Build Windows (PyInstaller)

on:
  push:
    tags:
      - "v*"   # solo se ejecuta en tags que empiecen por v, ej: v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt pip install -r requirements.txt
          pip install pyinstaller
        shell: cmd

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --clean --noconsole --onedir ^
            --name DTF_Pricing_Calculator ^
            --icon PresupuestosDTF.ico ^
            main.py
        shell: cmd

      - name: Zip dist
        run: |
          powershell -NoProfile -Command ^
            "Add-Type -AssemblyName 'System.IO.Compression.FileSystem'; ^
             [IO.Compression.ZipFile]::CreateFromDirectory('dist\\DTF_Pricing_Calculator','dist\\DTF_Pricing_Calculator.zip','Optimal',$false)"
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DTF_Pricing_Calculator
          path: dist/DTF_Pricing_Calculator.zip
          if-no-files-found: error

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/DTF_Pricing_Calculator.zip
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Build generado automáticamente para la versión ${{ github.ref_name }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
